karpatkey/execution-app

- src/components/Layout/Header.tsx
- src/contexts/reducers.ts
- src/contexts/types.ts
- src/pages/positions/[id]/index.tsx
- src/pages/positions/index.tsx
> feat: Polish some stuff

- src/components/PaperSection.tsx
- src/contexts/reducers.ts
- src/pages/positions/index.tsx
- src/views/Positions/WrapperPositions.tsx
> feat: add search, improve reducer

- src/views/Position/Form.tsx
> feat: add dialog

- .github/workflows/docker.yml
- Dockerfile
> ci: add Dockerfile and CI

- README.md
- src/components/Layout/Header.tsx
- src/config/strategies.example.json
- src/views/Position/Form.tsx
> feat: add snackbar

- src/config/strategies.json
> feat: change path

- src/config/strategies.json
- src/config/strategiesManager.tsx
- src/pages/api/execute.ts
- src/views/Position/Detail.tsx
- src/views/Position/Form.tsx
> WIP: add new json integration

- src/views/Position/Form.tsx
Update button texts
No issue related
> feat: update button texts

- .gitignore
- package.json
- src/config/constants.ts
- src/scripts/dump/loadEnv.ts
- src/scripts/dump/positions.ts
- tsconfig.json
- yarn.lock
Bulk collection of positions
No issue related
> feat: add bulk script

- .github/dependabot.yml
Update dependabot config
No issue related
> feat: update dependabot configuration

- .env.example
> feat: improve env example

- src/config/strategies/manager.tsx
- src/pages/api/execute.ts
- src/views/Position/Form.tsx
> feat: add support for parameters in a dynamic way

- src/views/Position/Form/Form.tsx
- src/views/Position/Form/InputRadio.tsx
- src/views/Position/Form/PercentageText.tsx
- src/views/Position/WrappedPosition.tsx
> fix: Feedback form integration

- src/pages/api/execute.ts
- src/views/Position/Form/Form.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
> feat: improve modal step part 5

- src/views/Position/Modal/Create/TransactionDetails.tsx
> feat: check for errors

- src/views/Position/Form/Form.tsx
> fix: Apply form feedback

- package.json
- src/pages/positions/[id]/index.tsx
- src/views/Position/Form/Form.tsx
- src/views/Position/Form/Label.tsx
- yarn.lock
> feat: Modal feedback

- src/views/Position/Form/Form.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
> feat: Feedback over modal

- src/contexts/reducers.ts
- src/contexts/state.ts
- src/pages/api/execute.ts
- src/utils/execute.ts
- src/views/Position/Form/Form.tsx
- src/views/Position/Modal/Create/SetupDetails.tsx
- src/views/Position/Modal/Create/TransactionCheck.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
- src/views/Position/Modal/Modal.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
> feat: Integrate tenderly action

- src/contexts/actions.ts
- src/contexts/reducers.ts
- src/contexts/state.ts
- src/pages/api/execute.ts
- src/pages/positions/[id]/index.tsx
- src/utils/execute.ts
- src/views/Position/Modal/Confirm/Confirm.tsx
- src/views/Position/Modal/Modal.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
> feat: integrate confirm

- src/pages/positions/[id]/index.tsx
> feat: add defaults

- src/views/Position/Modal/Confirm/Confirm.tsx
> feat: add new url

- src/views/Position/Modal/Confirm/Confirm.tsx
> feat: update url

- src/utils/execute.ts
> feat: add regex to fix value

- src/contexts/reducers.ts
- src/views/Position/Modal/Confirm/Confirm.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
- src/views/Position/Modal/Stepper.tsx
> feat: feedback

- .github/workflows/docker.yml
- Dockerfile
> fix: ci and dockerfile

- .github/workflows/docker.yml
- Dockerfile
Reverts karpatkey/panic-button-app#277
> Revert "fix: ci and dockerfile"

- src/views/Position/Form/Form.tsx
> feat: remove max button for slippage

- .github/workflows/docker.yml
> remove caching!

- .gitignore
- src/views/Position/Modal/Confirm/Confirm.tsx
> feat: hide cancel button

- src/pages/positions/[id]/index.tsx
- src/utils/execute.ts
- src/views/Position/Form/Form.tsx
- src/views/Position/Modal/Confirm/Confirm.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
- src/views/Position/Modal/Modal.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
> feat: add enhancements to the modal

- src/views/Position/Form/Form.tsx
- src/views/Position/WrappedPosition.tsx
> feat: add position detail enhancements

- src/components/Layout/Footer.tsx
- src/contexts/state.ts
- src/views/Positions/WrapperPositions.tsx
> feat: add order by active

- Dockerfile.dev
- Dockerfile.main
> feat: add improvement docker file

- Dockerfile.dev
- Dockerfile.main
> feat: update alpine version

- src/views/Positions/List.tsx
> feat: remove animation

- src/pages/positions/[id]/index.tsx
> feat: update submodule

- src/views/Position/Modal/Confirm/Confirm.tsx
> feat: remove text and add dot

- src/utils/execute.ts
- src/views/Position/Modal/Create/TransactionCheck.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
> feat: add improvements to the workflow

- src/contexts/reducers.ts
- src/pages/api/execute.ts
- src/pages/positions/[id]/index.tsx
- src/views/Position/Modal/Confirm/Confirm.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
> hotfix: details with DAOs

- src/contexts/reducers.ts
- src/pages/positions/index.tsx
- src/services/classes/dataWarehouse.class.ts
> fix: problem with dao filter

- docker-compose.yml
- src/pages/api/execute.ts
- src/utils/execute.ts
- src/views/Position/Modal/Confirm/Confirm.tsx
- src/views/Position/Modal/Create/TransactionDetails.tsx
- src/views/Position/Modal/Simulation/Tenderly.tsx
> feat: improve error handling

- docker-compose.yml
> feat: remove

- .env.example
> Fixed bug in env variable

- src/utils/execute.ts
> feat: remove quotes

- src/utils/execute.ts
> Release with fix in value quotes

- Dockerfile.dev
- src/config/strategies/manager.tsx
Fix namings of the ltd, because roles_royce changed namings
> feat: fix namings in ltd jsons titles

- .github/workflows/docker.yml
BREAKING CHANGE: Docker building fails
> fix(fix in docker build): fix in docker

- .github/workflows/docker.yml
- Dockerfile.dev
- Dockerfile.main
- pyproject.toml
- requirements.txt
> Fix docker build

- .github/workflows/docker.yml
- Dockerfile.dev
- Dockerfile.main
- pyproject.toml
- requirements.txt
Reverts karpatkey/panic-button-app#406
> Revert "Fix docker build"

- .github/workflows/pr-review.yml
- Dockerfile.dev
Fix the docker build as per the roles_royce upgrade.
> fix: clone submodule not shallow

- .github/workflows/docker.yml
- Dockerfile.main
> ci: add git in context

- .github/workflows/docker.yml
- Dockerfile.dev
- Dockerfile.main
> ci: docker fix

- .github/workflows/docker.yml
> ci: docker fix 2

- src/views/Position/Form/PercentageText.tsx
> Update roles_royce submodule

- src/views/Position/Form/Form.tsx
> fix: allow 0 in the form fields

- ingress-template.yaml
> fix: ingress template, add buffer

- deployment-template.yaml
> fix deployment template for pr review

- .github/workflows/docker.yml
> fix: pr-review deployment issue

- .dockerignore
- .github/workflows/docker.yml
- .gitignore
- Dockerfile
- deployment-template.yaml
- docker-compose.yml
- next.config.js
- package.json
- run.sh
- tsconfig.json
- yarn.lock
> Improve dockerfile

- src/services/classes/dataWarehouse.class.ts
> Fix queries

- .github/workflows/merge-dependabot.yml
- package.json
- yarn.lock
> Dependencies

- .github/workflows/docker.yml
- .github/workflows/pr-comment.yml
- README.md
- delete-deployment-script.sh
- deploy-script.sh
- deployment-template.yaml
- ingress-template.yaml
- next.config.js
- package.json
- pyproject.toml
We need to change repo name also roles_royce app folder as well!
Do no merge this PR!
> Namechange

- .github/workflows/pr-comment.yml
- deploy-script.sh
> little changes

- .github/workflows/docker.yml
> Adding Semver with date and time
